/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    BarraSuperior: typeof import('./src/components/AppBar.vue')['default']
    BotonBuscarDoc: typeof import('./src/components/paginaBuscarDocente/botonBuscarDoc.vue')['default']
    BotonBuscarEst: typeof import('./src/components/paginaBuscar/botonBuscarEst.vue')['default']
    BotonSemestre: typeof import('./src/components/paginaBuscar/botonSemestre.vue')['default']
    Drawer: typeof import('./src/components/drawer.vue')['default']
    DropDownButton: typeof import('./src/components/paginaBuscar/dropDownButton.vue')['default']
    DropDownButtonBorrar: typeof import('./src/components/paginaBorrar/dropDownButtonBorrar.vue')['default']
    DropDownButtonCom: typeof import('./src/components/paginaCompleta/dropDownButtonCom.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/paginaBuscar/SearchBar.vue')['default']
    Tabla: typeof import('./src/components/tabla.vue')['default']
    TablaBorrarAsig: typeof import('./src/components/paginaBorrar/tablaBorrarAsig.vue')['default']
    TablaBorrarDoc: typeof import('./src/components/paginaBorrar/tablaBorrarDoc.vue')['default']
    TablaBorrarEst: typeof import('./src/components/paginaBorrar/tablaBorrarEst.vue')['default']
    TablaDeUnRegistro: typeof import('./src/components/paginaBuscar/tablaDeUnRegistro.vue')['default']
    TablaDeUnRegistroAsig: typeof import('./src/components/paginaBuscarAsignaturas/tablaDeUnRegistroAsig.vue')['default']
    TablaDeUnRegistroAsigCom: typeof import('./src/components/paginaCompleta/tablaDeUnRegistroAsigCom.vue')['default']
    TablaDeUnRegistroBorrarAsig: typeof import('./src/components/paginaBorrar/tablaDeUnRegistroBorrarAsig.vue')['default']
    TablaDeUnRegistroBorrarDoc: typeof import('./src/components/paginaBorrar/tablaDeUnRegistroBorrarDoc.vue')['default']
    TablaDeUnRegistroBorrarEst: typeof import('./src/components/paginaBorrar/tablaDeUnRegistroBorrarEst.vue')['default']
    TablaDeUnRegistroDoc: typeof import('./src/components/paginaBuscarDocente/tablaDeUnRegistroDoc.vue')['default']
    TablaDeUnRegistroDocCom: typeof import('./src/components/paginaCompleta/tablaDeUnRegistroDocCom.vue')['default']
    TablaDeUnRegistroEstCom: typeof import('./src/components/paginaCompleta/tablaDeUnRegistroEstCom.vue')['default']
    TablaPrincipal: typeof import('./src/components/paginaBuscar/tablaPrincipal.vue')['default']
    TablaPrincipalAsig: typeof import('./src/components/paginaBuscarAsignaturas/tablaPrincipalAsig.vue')['default']
    TablaPrincipalAsigCom: typeof import('./src/components/paginaCompleta/tablaPrincipalAsigCom.vue')['default']
    TablaPrincipalDoc: typeof import('./src/components/paginaBuscarDocente/tablaPrincipalDoc.vue')['default']
    TablaPrincipalDocCom: typeof import('./src/components/paginaCompleta/tablaPrincipalDocCom.vue')['default']
    TablaPrincipalEstCom: typeof import('./src/components/paginaCompleta/tablaPrincipalEstCom.vue')['default']
    TablaSecundariaAsig: typeof import('./src/components/paginaBuscarAsignaturas/tablaSecundariaAsig.vue')['default']
    TablaSecundariaAsigCom: typeof import('./src/components/paginaCompleta/tablaSecundariaAsigCom.vue')['default']
    TablaSecundariaDoc: typeof import('./src/components/paginaBuscarDocente/tablaSecundariaDoc.vue')['default']
    TablaSecundariaDocCom: typeof import('./src/components/paginaCompleta/tablaSecundariaDocCom.vue')['default']
    TablaSecundariaEst: typeof import('./src/components/paginaBuscar/tablaSecundariaEst.vue')['default']
    TablaSecundariDoc: typeof import('./src/components/paginaBuscarDocente/tablaSecundariaDoc.vue')['default']
    TablaSecundariEstCom: typeof import('./src/components/paginaCompleta/TablaSecundariEstCom.vue')['default']
    TablaTerciariaAsig: typeof import('./src/components/paginaBuscarAsignaturas/tablaTerciariaAsig.vue')['default']
    TablaTerciariaAsigCom: typeof import('./src/components/paginaCompleta/tablaTerciariaAsigCom.vue')['default']
    TablaTerciariaDoc: typeof import('./src/components/paginaBuscarDocente/tablaTerciariaDoc.vue')['default']
    TablaTerciariaDocCom: typeof import('./src/components/paginaCompleta/tablaTerciariaDocCom.vue')['default']
    TablaTerciariaEst: typeof import('./src/components/paginaBuscar/tablaTerciariaEst.vue')['default']
    TablaTerciariaEstCom: typeof import('./src/components/paginaCompleta/tablaTerciariaEstCom.vue')['default']
    TarjetaImagenTexto: typeof import('./src/components/paginaprincipal/TarjetaImagenTexto.vue')['default']
  }
}
