/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/paginaActualizar': RouteRecordInfo<'/paginaActualizar', '/paginaActualizar', Record<never, never>, Record<never, never>>,
    '/paginaBorrar': RouteRecordInfo<'/paginaBorrar', '/paginaBorrar', Record<never, never>, Record<never, never>>,
    '/paginaBorrarAsig': RouteRecordInfo<'/paginaBorrarAsig', '/paginaBorrarAsig', Record<never, never>, Record<never, never>>,
    '/paginaBorrarDoc': RouteRecordInfo<'/paginaBorrarDoc', '/paginaBorrarDoc', Record<never, never>, Record<never, never>>,
    '/paginaBorrarEst': RouteRecordInfo<'/paginaBorrarEst', '/paginaBorrarEst', Record<never, never>, Record<never, never>>,
    '/paginaBuscar': RouteRecordInfo<'/paginaBuscar', '/paginaBuscar', Record<never, never>, Record<never, never>>,
    '/paginaBuscarAsig': RouteRecordInfo<'/paginaBuscarAsig', '/paginaBuscarAsig', Record<never, never>, Record<never, never>>,
    '/paginaBuscarAsigCom': RouteRecordInfo<'/paginaBuscarAsigCom', '/paginaBuscarAsigCom', Record<never, never>, Record<never, never>>,
    '/paginaBuscarDocCom': RouteRecordInfo<'/paginaBuscarDocCom', '/paginaBuscarDocCom', Record<never, never>, Record<never, never>>,
    '/paginaBuscarDoce': RouteRecordInfo<'/paginaBuscarDoce', '/paginaBuscarDoce', Record<never, never>, Record<never, never>>,
    '/paginaBuscarEstudiante': RouteRecordInfo<'/paginaBuscarEstudiante', '/paginaBuscarEstudiante', Record<never, never>, Record<never, never>>,
    '/paginaBuscarEstudianteCom': RouteRecordInfo<'/paginaBuscarEstudianteCom', '/paginaBuscarEstudianteCom', Record<never, never>, Record<never, never>>,
    '/paginaCompleta': RouteRecordInfo<'/paginaCompleta', '/paginaCompleta', Record<never, never>, Record<never, never>>,
    '/principal': RouteRecordInfo<'/principal', '/principal', Record<never, never>, Record<never, never>>,
  }
}
